### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by ctaggart** [isaacabraham/azure-fsharp-helpers#4]
Hey @isaacabraham, is this code MIT license or something else?

**Comment by isaacabraham** [comment]
Ummm. I've never put a license here - you can use it however you wish :-) If you'd like to put a "standard" license in there (MIT or whatever is normal) then please submit a PR and I'll review and accept? Thanks!

**Comment by ctaggart** [comment]
Thanks! Added MIT license in #5.
